---
title: "R Notebook"
output: html_notebook
---


```{r}
plot(cars)


model1 <- lm(formula=speed~dist,data=cars,)
summary(model1)


```


```{r}
options(scipen=999) 
 
oj_fpath <- "/Users/sathishrajendiran/Documents/week_7_data_set.csv"
 
  # function readFiles
  readFiles <- function(fpath)
    {
    dftemp <- data.frame(read.csv(fpath),stringsAsFactors=FALSE)
    return(dftemp)
    }
  
  oj <- readFiles(oj_fpath) 
  
  summary(oj)
  
  model2 <- lm(formula=price~brand, data = oj)
  
  summary(model2)
```
```{r}
library(ggplot2)
x <- c(1:10)
y <- c(1:10)

df <- data.frame(x,y)

plot(df)


m <- lm(formula = y~x,data = df)
summary(m)
abline(m)


x <- c(1,2,3,4,5)
y <- c(0.2,2.2,3.8,4.9,5.1)
dfnew <- data.frame(x,y)
plot(dfnew)

m1 <- lm(formula = y~x,data = dfnew)
summary(m1)

g <- ggplot(dfnew,aes(x=x,y=y))+geom_point()
g
g+geom_smooth(method = "lm",color="red")

w <- c(1,3,4,4.5,5,6.1,7.3,7.9,9.2,10.05)

dfnew <- data.frame(x,y,w)
dfnew

plot(dfnew$x,dfnew$w)


m2 <- lm(formula = w~x,data = dfnew)
summary(m2)

g1 <- ggplot(dfnew,aes(x=x,y=w))+geom_point()

g1+geom_smooth(method = "lm",color="red")


```


```{r}

x <- sample(1:100,10,replace = FALSE)
y <- sample(1:100,10,replace = FALSE)

df1 <- data.frame(x,y)

plot(x,y)

m3 <- lm(formula = x~y,data = df1)
summary(m3)

g2 <- ggplot(df1,aes(x=x,y=y))+geom_point()

g2+geom_smooth(method = "lm",color="red")

```


```{r}

mtcars[1:4,]
colnames(mtcars)

mpgWT.lm <- lm(formula = mpg ~wt,data = mtcars)
summary(mpgWT.lm)

g3 <- ggplot(mtcars,aes(x=mpg,y=wt))+geom_point()

g3+geom_smooth(method = "lm",color="red")



mpgHP.lm <- lm(formula = mpg ~hp,data = mtcars)
summary(mpgHP.lm)


mpgHPWT.lm <- lm(formula = mpg ~hp+wt,data = mtcars)
summary(mpgHPWT.lm)


mpgWTCY.lm <- lm(formula = mpg ~wt+cyl,data = mtcars)
summary(mpgWTCY.lm)


mpgAll.lm <- lm(formula = mpg ~.,data = mtcars)
summary(mpgAll.lm)


range(mtcars$wt)

newdata <- data.frame(cyl=4,wt=2.8)
newdata

predict(mpgWTCY.lm,newdata,type="response")

newdata <- data.frame(cyl=4,wt=1.8)
predict(mpgWTCY.lm,newdata,type="response")

```

```{r}
mtcars[mtcars$hp > 110 & mtcars$hp < 240,]
summ <- summary(mpgWTCY.lm)
summ
paste("p-values:")
summ$coefficients[,4]
paste("adjusted r-squared:" ,summ$adj.r.squared)
str(summ)
```


```{r}
g4 <- ggplot(mtcars,aes(x=hp,y=wt))+geom_point(aes(size=mpg,color=mpg))

g4+geom_smooth(method = "lm",color="red")

```

